Final, I think.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -52,7 +52,7 @@ jobs:
           git checkout --orphan deploy
 
           # Remove all files and directories except 'out'
-          find . -mindepth 1 -not -path './out*' -exec rm -rf {} + || echo "Some files were not found and could not be deleted"
+          find . -mindepth 1 -not -path './out*' -not -path './.git*' -exec rm -rf {} + || echo "Some files were not found and could not be deleted"
 
           # Check if the 'out' directory exists and copy its contents
           if [ -d "./out" ]; then
